server:
  port: 8080

spring:
  application:
    name: service-b
  config:
    import: optional:file:/etc/secrets/db/

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  tracing:
    sampling:
      probability: 1.0 # 100% sampling for development

  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs

service:
  name: "Service B"
  description: "Demo service"
  version: "0.0.1"