apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: service-a
  namespace: services
spec:
  interval: 1m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./apps/service-a/helm
      sourceRef:
        kind: GitRepository
        name: platform-gitops
        namespace: flux-system
  values:
    image:
      repository: agilesolutions/service-a
      tag: 0.0.7
    service:
      port: 8080
    ingress:
      enabled: true
      className: nginx
      host: service-a.local
