apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app: {{ include "app.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "app.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}